# Ansible Inventory File
# Generated by Terraform for Proxmox VMs
# This file is automatically created - do not edit manually

all:
  children:
    proxmox_vms:
      hosts:
%{ for vm in vms ~}
        ${vm.name}:
          ansible_host: ${vm.ip}
          ansible_user: ${vm.user}
          ansible_ssh_private_key_file: ${ssh_private_key}
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
          vm_name: ${vm.name}
          vm_ip: ${vm.ip}
%{ endfor ~}
      vars:
        ansible_python_interpreter: /usr/bin/python3
        ansible_ssh_pipelining: true
        ansible_ssh_retries: 3
        ansible_timeout: 30

# Group variables for all Proxmox VMs
    proxmox_vms:
      vars:
        # Common configuration
        deployment_method: terraform
        infrastructure_type: proxmox
        managed_by: proxmox-ai-assistant
        
        # Security settings
        security_hardening: true
        firewall_enabled: true
        fail2ban_enabled: true
        
        # System settings
        timezone: UTC
        ntp_servers:
          - 0.pool.ntp.org
          - 1.pool.ntp.org
          - 2.pool.ntp.org
          - 3.pool.ntp.org
        
        # Package management
        auto_updates: true
        extra_packages:
          - htop
          - vim
          - curl
          - wget
          - git
          - unzip

# Example usage:
# ansible-playbook -i inventory/hosts.yml playbooks/site.yml
# ansible proxmox_vms -i inventory/hosts.yml -m ping
# ansible proxmox_vms -i inventory/hosts.yml -m setup